# Generated by Django 4.0.5 on 2022-07-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
    ]
