# Generated by Django 4.0.5 on 2022-07-25 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0002_remove_curso_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='coder_app.curso')),
            ],
        ),
    ]
